apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-abofi-pvc
  namespace: promptsales
  labels:
    app: sqlserver-abofi
    component: database
    owner: abofi
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Ajustado para uso personal  
