apiVersion: v1
kind: Secret
metadata:
  name: promptads-secret
  namespace: promptads
type: Opaque
stringData:
  # IMPORTANTE: Cambiar esta contraseña en producción
  # Debe tener al menos 8 caracteres con mayúsculas, minúsculas, números y símbolos
  SA_PASSWORD: "AleeCR27"
