apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: promptads-networkpolicy
  namespace: promptads
  labels:
    app: promptads
    tier: database
spec:
  podSelector:
    matchLabels:
      app: promptads
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app: promptsales
      ports:
        - protocol: TCP
          port: 1433
  egress:
    # Permitir DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Permitir comunicación con PromptCRM (linked server)
    - to:
        - namespaceSelector:
            matchLabels:
              component: crm
      ports:
        - protocol: TCP
          port: 1433
    # Permitir comunicación con PostgreSQL (PromptSales)
    - to:
        - namespaceSelector:
            matchLabels:
              component: central
      ports:
        - protocol: TCP
          port: 5432
