apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promptads-backup
  namespace: promptads
  labels:
    app: promptads
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: standard
