apiVersion: v1
kind: Secret
metadata:
  name: promptads-db-secret
  namespace: promptads
type: Opaque
stringData:
  SQLSERVER_HOST: "172.26.0.1"
  SQLSERVER_PORT: "1433"
  SQLSERVER_DB: "PromptAds"
  SQLSERVER_USER: "promptads_app"
  SQLSERVER_PASSWORD: "123456789"
