apiVersion: v1
kind: Secret
metadata:
  name: promptcontent-secrets
  namespace: promptcontent-dev
  labels:
    app: promptcontent
type: Opaque
stringData:
  # Reemplazar con tu cadena real (por ejemplo: mongodb://user:pass@host:27017/db)
  # k8s/promptcontent/secrets.placeholders.yaml
  MONGODB_URI: "mongodb://host.minikube.internal:27017/promptContent"
  MONGODB_DB_NAME: "promptContent"
  # Pinecone para almacenamiento vectorial
  PINECONE_API_KEY: "<reemplaza-con-tu-api-key>"
  PINECONE_INDEX: "promptcontent"
  # API interno para autenticar llamadas MCP/HTTP
  API_KEY: "devlocal"
  # Integraci√≥n externa (Spotify Client Credentials)
  SPOTIFY_CLIENT_ID: "eb52b5e4731c4d7c8f6a3d83193e4388"
  SPOTIFY_CLIENT_SECRET: "d011d354964c4852a88b5638e717ad55"
