apiVersion: v1
kind: Secret
metadata:
  name: promptcontent-secrets
  namespace: promptcontent-dev
  labels:
    app: promptcontent
type: Opaque
stringData:
  MONGODB_URI: "mongodb://host.minikube.internal:27017/promptContent"
  MONGODB_DB_NAME: "promptContent"
  PGVECTOR_DSN: "postgres://postgres:postgres@postgres:5432/promptcontent"
  PGVECTOR_TABLE: "content_embeddings"
  PGVECTOR_DIM: "128"
  API_KEY: "devlocal"
  SPOTIFY_CLIENT_ID: "eb52b5e4731c4d7c8f6a3d83193e4388"
  SPOTIFY_CLIENT_SECRET: "d011d354964c4852a88b5638e717ad55"
