apiVersion: v1
kind: Service
metadata:
  name: promptcontent-svc-prod
  namespace: promptcontent-dev
  labels:
    app: promptcontent
    tier: prod
spec:
  type: LoadBalancer
  selector:
    app: promptcontent
  ports:
    - name: http
      port: 80
      targetPort: http

