apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-hba-cm
  namespace: promptcontent-dev
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::0/0                   md5
