apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: promptcontent-dev
  labels:
    app: postgres
    tier: database
type: Opaque
stringData:
  POSTGRES_DB: "PromptContent"
  POSTGRES_USER: "User"
  POSTGRES_PASSWORD: "UserPassword123!"
